name: final_env
channels:
  - conda-forge
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - accelerate>=0.12.0
  - pytorch>=1.3.0
  - datasets<=2.21.0
  - sentencepiece!=0.1.92                 
  - protobuf                      
  - evaluate
  - transformers
  - scikit-learn